# Generated by Django 5.2.12 on 2026-03-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                (
                    "physical_completion_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "financial_disbursement_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "burn_variance_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("delayed_days", models.IntegerField(default=0)),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("flagged_count", models.PositiveIntegerField(default=0)),
                ("approved_milestones", models.PositiveIntegerField(default=0)),
                ("total_milestones", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
