# Generated by Django 5.2.12 on 2026-04-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("scope_type", models.CharField(default="GLOBAL", max_length=20)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("lga", models.CharField(blank=True, max_length=100)),
                ("total_projects", models.PositiveIntegerField(default=0)),
                ("active_projects", models.PositiveIntegerField(default=0)),
                ("flagged_projects_count", models.PositiveIntegerField(default=0)),
                ("delayed_projects_count", models.PositiveIntegerField(default=0)),
                ("total_budget", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("awaiting_verification_count", models.PositiveIntegerField(default=0)),
                ("completed_projects_count", models.PositiveIntegerField(default=0)),
                ("high_risk_projects_count", models.PositiveIntegerField(default=0)),
                ("independent_validation_required_count", models.PositiveIntegerField(default=0)),
                ("delayed_milestones_count", models.PositiveIntegerField(default=0)),
                ("unresolved_fraud_flags_count", models.PositiveIntegerField(default=0)),
                ("geofence_exceptions_pending_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="portfoliometricsnapshot",
            constraint=models.UniqueConstraint(
                fields=("snapshot_date", "scope_type", "state", "lga"),
                name="analytics_unique_portfolio_snapshot_scope",
            ),
        ),
    ]
