export type Project = {
  id: number;
  project_code: string;
  title: string;
  description?: string;
  state: string;
  lga: string;
  site_address: string;
  contractor?: { id: number; name: string } | null;
  latitude: number;
  longitude: number;
  geo_fence_radius_meters: number;
  current_status: string;
  risk_status: string;
  requires_independent_validation: boolean;
  budget_amount?: string;
  lifecycle_stage?: string;
  health_score?: number;
  health_band?: string;
  alerts?: Array<{
    code: string;
    severity: string;
    message: string;
  }>;
  physical_completion_percent?: number;
  financial_disbursement_percent?: number;
  burn_variance_percent?: number;
  delayed_days?: number;
  total_milestones?: number;
  approved_milestones?: number;
  overdue_milestones?: number;
  evidence_submissions_count?: number;
  open_fraud_flags?: number;
  pending_geofence_exceptions?: number;
};
