import { ROLES } from "@/lib/constants/roles";

export const DASHBOARD_ACCESS_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.PROGRAM_DIRECTOR,
  ROLES.M_E_OFFICER,
  ROLES.QA_OFFICER,
  ROLES.FINANCE_OFFICER,
  ROLES.AUDITOR
] as const;

export const PROJECT_ACCESS_ROLES = DASHBOARD_ACCESS_ROLES;

export const PROJECT_CREATE_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.PROGRAM_DIRECTOR,
  ROLES.M_E_OFFICER
] as const;

export const MILESTONE_REVIEW_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.QA_OFFICER,
  ROLES.M_E_OFFICER
] as const;

export const FINANCE_QUEUE_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.FINANCE_OFFICER,
  ROLES.PROGRAM_DIRECTOR
] as const;

export const DISBURSEMENT_ACCESS_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.FINANCE_OFFICER,
  ROLES.PROGRAM_DIRECTOR,
  ROLES.AUDITOR
] as const;

export const ANALYTICS_ACCESS_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.PROGRAM_DIRECTOR,
  ROLES.AUDITOR
] as const;

export const AUDIT_ACCESS_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.AUDITOR,
  ROLES.PROGRAM_DIRECTOR
] as const;

export const GEOFENCE_EXCEPTION_REVIEW_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.PROGRAM_DIRECTOR,
  ROLES.AUDITOR,
  ROLES.QA_OFFICER
] as const;
