export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  PROGRAM_DIRECTOR: "PROGRAM_DIRECTOR",
  M_E_OFFICER: "M_E_OFFICER",
  FIELD_OFFICER: "FIELD_OFFICER",
  CONTRACTOR: "CONTRACTOR",
  QA_OFFICER: "QA_OFFICER",
  FINANCE_OFFICER: "FINANCE_OFFICER",
  AUDITOR: "AUDITOR"
} as const;