export const PROJECT_STATUSES = [
  "NOT_STARTED",
  "ACTIVE",
  "AWAITING_VERIFICATION",
  "APPROVED_FOR_FUNDING",
  "DELAYED",
  "FLAGGED",
  "COMPLETED",
  "SUSPENDED"
];

export const MILESTONE_STATUSES = [
  "PENDING",
  "OPEN_FOR_SUBMISSION",
  "SUBMITTED",
  "UNDER_REVIEW",
  "REWORK_REQUIRED",
  "APPROVED",
  "REJECTED",
  "FLAGGED"
];