# Generated by Django 5.2.12 on 2026-03-21 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "default_evidence_type",
                    models.CharField(default="PHOTO", max_length=50),
                ),
                (
                    "default_required_evidence_count",
                    models.PositiveIntegerField(default=1),
                ),
                ("default_qa_required", models.BooleanField(default=True)),
                (
                    "default_requires_field_validation",
                    models.BooleanField(default=False),
                ),
                (
                    "default_tolerance_rules_json",
                    models.JSONField(blank=True, default=dict),
                ),
                ("sequence_order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("sequence_order", models.PositiveIntegerField()),
                (
                    "expected_evidence_type",
                    models.CharField(default="PHOTO", max_length=50),
                ),
                ("required_evidence_count", models.PositiveIntegerField(default=1)),
                ("required_video_count", models.PositiveIntegerField(default=0)),
                ("qa_required", models.BooleanField(default=True)),
                ("requires_field_validation", models.BooleanField(default=False)),
                ("required_checklist_score", models.PositiveIntegerField(default=70)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN_FOR_SUBMISSION", "Open For Submission"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("REWORK_REQUIRED", "Rework Required"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PENDING",
                        max_length=50,
                    ),
                ),
                ("approval_sequence_json", models.JSONField(blank=True, default=list)),
                ("tolerance_rules_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_tranche",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_milestone",
                        to="finance.fundingtranche",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="milestones.milestonetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
                "unique_together": {("project", "sequence_order")},
            },
        ),
        migrations.CreateModel(
            name="MilestoneChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                ("max_score", models.PositiveIntegerField(default=10)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                (
                    "project_milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="milestones.projectmilestone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MilestoneDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(default="FINISH_TO_START", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "depends_on_milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependents",
                        to="milestones.projectmilestone",
                    ),
                ),
                (
                    "project_milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="milestones.projectmilestone",
                    ),
                ),
            ],
            options={
                "unique_together": {("project_milestone", "depends_on_milestone")},
            },
        ),
    ]
