# Generated by Django 5.2.12 on 2026-03-21 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualOverrideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "supporting_document_path",
                    models.CharField(blank=True, max_length=500),
                ),
                ("current_status", models.CharField(default="PENDING", max_length=30)),
                ("risk_acknowledged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrancheEligibilitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
                ("is_eligible", models.BooleanField(default=False)),
                ("rules_passed_json", models.JSONField(default=list)),
                ("rules_failed_json", models.JSONField(default=list)),
                ("evaluated_by_system", models.BooleanField(default=True)),
                ("snapshot_hash", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="FundingTranche",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tranche_number", models.PositiveIntegerField()),
                ("tranche_name", models.CharField(max_length=255)),
                (
                    "planned_amount",
                    models.DecimalField(decimal_places=2, max_digits=16),
                ),
                (
                    "percentage_of_budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("planned_release_date", models.DateField(blank=True, null=True)),
                ("actual_release_date", models.DateField(blank=True, null=True)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Locked"),
                            ("ELIGIBLE", "Eligible"),
                            ("DISBURSED", "Disbursed"),
                            ("ON_HOLD", "On Hold"),
                            ("OVERRIDE_PENDING", "Override Pending"),
                            ("OVERRIDE_APPROVED", "Override Approved"),
                        ],
                        default="LOCKED",
                        max_length=30,
                    ),
                ),
                ("unlock_status", models.CharField(default="LOCKED", max_length=30)),
                ("unlock_reason", models.TextField(blank=True)),
                ("release_reference", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="projects.project",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tranche_number"],
            },
        ),
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                ("payment_reference", models.CharField(max_length=255)),
                ("note", models.TextField(blank=True)),
                (
                    "source_of_authority",
                    models.CharField(default="SYSTEM_ELIGIBLE", max_length=100),
                ),
                (
                    "authorized_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disbursements_authorized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="projects.project",
                    ),
                ),
                (
                    "released_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tranche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disbursements",
                        to="finance.fundingtranche",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManualOverrideApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision", models.CharField(max_length=30)),
                ("comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
