# Generated by Django 5.2.12 on 2026-03-21 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance", "0001_initial"),
        ("milestones", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manualoverriderequest",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="milestones.projectmilestone",
            ),
        ),
        migrations.AddField(
            model_name="manualoverriderequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="override_requests",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="manualoverriderequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="manualoverriderequest",
            name="tranche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="override_requests",
                to="finance.fundingtranche",
            ),
        ),
        migrations.AddField(
            model_name="manualoverrideapproval",
            name="override_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="finance.manualoverriderequest",
            ),
        ),
        migrations.AddField(
            model_name="trancheeligibilitysnapshot",
            name="tranche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="eligibility_snapshots",
                to="finance.fundingtranche",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fundingtranche",
            unique_together={("project", "tranche_number")},
        ),
    ]
