# Generated by Django 5.2.12 on 2026-03-21 21:23

import apps.evidence.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaptureAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_time", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("distance_from_site_meters", models.FloatField()),
                ("within_geofence", models.BooleanField(default=False)),
                ("result", models.CharField(max_length=30)),
                ("reason_code", models.CharField(blank=True, max_length=100)),
                ("device_metadata_json", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.evidence.models.evidence_upload_path
                    ),
                ),
                ("file_type", models.CharField(max_length=30)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size_bytes", models.BigIntegerField()),
                ("sha256_hash", models.CharField(max_length=128)),
                ("perceptual_hash", models.CharField(blank=True, max_length=128)),
                ("captured_at", models.DateTimeField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("accuracy_meters", models.FloatField(blank=True, null=True)),
                ("bearing", models.FloatField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EvidenceSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_by_actor_type", models.CharField(max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("CONTRACTOR", "Contractor"),
                            ("FIELD_OFFICER", "Field Officer"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "submission_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("BLOCKED", "Blocked"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REWORK_REQUIRED", "Rework Required"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("device_platform", models.CharField(blank=True, max_length=50)),
                (
                    "capture_mode",
                    models.CharField(default="LIVE_IN_APP", max_length=50),
                ),
                ("offline_created_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "geo_validation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("EXCEPTION_REQUESTED", "Exception Requested"),
                            ("EXCEPTION_APPROVED", "Exception Approved"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "integrity_status",
                    models.CharField(default="PENDING", max_length=30),
                ),
                ("requires_exception_review", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeoFenceExceptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_latitude", models.FloatField()),
                ("current_longitude", models.FloatField()),
                ("distance_from_site_meters", models.FloatField()),
                ("reason", models.TextField()),
                ("status", models.CharField(default="PENDING", max_length=30)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
