# Generated by Django 5.2.12 on 2026-03-21 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evidence", "0001_initial"),
        ("milestones", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="captureattempt",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="milestones.projectmilestone",
            ),
        ),
        migrations.AddField(
            model_name="captureattempt",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="captureattempt",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidencesubmission",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="milestones.projectmilestone",
            ),
        ),
        migrations.AddField(
            model_name="evidencesubmission",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence_submissions",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="evidencesubmission",
            name="submitted_by_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="evidence_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="evidence.evidencesubmission",
            ),
        ),
        migrations.AddField(
            model_name="geofenceexceptionrequest",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="milestones.projectmilestone",
            ),
        ),
        migrations.AddField(
            model_name="geofenceexceptionrequest",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="geofenceexceptionrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="geofenceexceptionrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_geofence_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="geofenceexceptionrequest",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="evidence.evidencesubmission",
            ),
        ),
    ]
