# Generated by Codex for InfraTrack runtime hardening.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencesubmission",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name="evidencesubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(idempotency_key__gt=""),
                fields=("submitted_by_user", "idempotency_key"),
                name="uniq_evid_idem_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencesubmission",
            index=models.Index(
                fields=["project", "milestone", "-created_at"],
                name="evid_proj_mst_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="evidencesubmission",
            index=models.Index(
                fields=["submitted_by_user", "idempotency_key"],
                name="evid_submit_idem_idx",
            ),
        ),
    ]
